"""add_total_points_duration_youtube_url_to_matches

Revision ID: 22e266f04f94
Revises: d4e76bff4d80
Create Date: 2025-06-13 03:12:58.046967

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '22e266f04f94'
down_revision = 'd4e76bff4d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True, comment='比賽總得分'))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='比賽時長(分鐘)'))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=500), nullable=True, comment='YouTube 連結'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###
