"""Add Organization model and link to Member, migrate existing org data

Revision ID: 25e8f95d7e75
Revises: 09c786489507
Create Date: 2025-05-31 16:43:55.955255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e8f95d7e75'
down_revision = '09c786489507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='組織/隊伍'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='所在城市'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_member_organization_id', 'organizations', ['organization_id'], ['id'])
        batch_op.drop_column('organization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='組織/單位'))
        batch_op.drop_constraint('fk_member_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
