"""init

Revision ID: 3dcdf7b283b0
Revises: 
Create Date: 2025-05-23 02:38:25.943020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcdf7b283b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False, comment='組織/隊伍全名'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='賽事名稱 (例：113學年度大專盃淘汰賽 vs 台灣大學)'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='賽事日期'),
    sa.Column('opponent_team_overall', sa.String(length=100), nullable=True, comment='對手隊伍總稱'),
    sa.Column('nature', sa.Enum('FRIENDLY', 'INTERNAL_RANKING', 'PRACTISE', 'NIAG', name='matchnatureenum'), nullable=True, comment='整體賽事性質'),
    sa.Column('venue', sa.String(length=100), nullable=True, comment='比賽地點'),
    sa.Column('event_notes', sa.Text(), nullable=True, comment='團隊賽事備註'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('student_id', sa.String(length=20), nullable=True, comment='學號'),
    sa.Column('organization_id', sa.String(length=20), nullable=True, comment='單位'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True, comment='性別'),
    sa.Column('position', sa.Enum('BACK', 'FRONT', 'VERSATILE', name='positionenum'), nullable=True, comment='位置'),
    sa.Column('score', sa.Integer(), nullable=False, comment='積分'),
    sa.Column('racket', sa.String(length=100), nullable=True, comment='球拍'),
    sa.Column('join_date', sa.Date(), nullable=True, comment='入隊日期'),
    sa.Column('leave_date', sa.Date(), nullable=True, comment='離隊日期'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否為現役隊員'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('match_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_type', sa.Enum('SINGLES', 'DOUBLES', 'MIXED_DOUBLES', name='match_type_enum_mr'), nullable=False),
    sa.Column('match_format', sa.Enum('TIEBREAK', 'FIVE_GAME_SET', 'SEVEN_GAME_SET', 'NINE_GAME_SET', name='match_format_enum_mr'), nullable=False, comment='賽制'),
    sa.Column('side_a_player1_id', sa.Integer(), nullable=False),
    sa.Column('side_a_player2_id', sa.Integer(), nullable=True),
    sa.Column('side_b_player1_id', sa.Integer(), nullable=False),
    sa.Column('side_b_player2_id', sa.Integer(), nullable=True),
    sa.Column('side_a_outcome', sa.Enum('WIN', 'LOSS', 'NOT_PLAYED', name='outcome_enum_mr'), nullable=False, comment='A方視角的比賽結果'),
    sa.Column('match_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['side_a_player1_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['side_a_player2_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['side_b_player1_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['side_b_player2_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='該球員本場比賽的特殊記錄'),
    sa.ForeignKeyConstraint(['match_id'], ['match_records.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='_match_player_stats_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('match_records')
    op.drop_table('team_members')
    op.drop_table('team_events')
    op.drop_table('rackets')
    op.drop_table('organizations')
    # ### end Alembic commands ###
