"""Change score fields to games_won in MatchRecord

Revision ID: 3f85c280139d
Revises: af252745d22b
Create Date: 2025-05-23 08:05:43.927029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f85c280139d'
down_revision = 'af252745d22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rackets')
    op.drop_table('organizations')
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_a_games_won', sa.Integer(), nullable=False, comment='A方贏得的總局數'))
        batch_op.add_column(sa.Column('side_b_games_won', sa.Integer(), nullable=False, comment='B方贏得的總局數'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.drop_column('side_b_games_won')
        batch_op.drop_column('side_a_games_won')

    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False, comment='組織/隊伍全名'),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey')),
    sa.UniqueConstraint('name', name=op.f('organizations_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('rackets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rackets_pkey'))
    )
    # ### end Alembic commands ###
