"""Baseline current schema as new initial migration

Revision ID: 43c872a57a3a
Revises: 
Create Date: 2025-06-02 20:00:17.144220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43c872a57a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('MEMBER', 'CADRE', 'ADMIN', name='user_role_enum_users'),
               type_=sa.Enum('MEMBER', 'CADRE', 'COACH', 'ADMIN', name='user_role'),
               existing_comment='使用者角色',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('MEMBER', 'CADRE', 'COACH', 'ADMIN', name='user_role'),
               type_=postgresql.ENUM('MEMBER', 'CADRE', 'ADMIN', name='user_role_enum_users'),
               existing_comment='使用者角色',
               existing_nullable=False)

    # ### end Alembic commands ###
