"""new db structure

Revision ID: 7ebb2e559042
Revises: 
Create Date: 2025-06-04 01:33:16.342593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebb2e559042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False, comment='比賽唯一識別碼'),
    sa.Column('match_date', sa.Date(), nullable=False, comment='比賽日期'),
    sa.Column('match_type', sa.Enum('singles', 'doubles', 'mixed_doubles', name='match_type_enum_matches'), nullable=False, comment='比賽類型 (單打、雙打、混雙)'),
    sa.Column('match_format', sa.Enum('games_5', 'games_7', 'games_9', name='match_format_enum_matches'), nullable=False, comment='賽制'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_match_date'), ['match_date'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False, comment='組織唯一識別碼'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='組織全名'),
    sa.Column('short_name', sa.String(length=30), nullable=True, comment='組織簡稱或代號'),
    sa.Column('description', sa.Text(), nullable=True, comment='組織描述'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='主要聯絡人'),
    sa.Column('contact_email', sa.String(length=120), nullable=True, comment='聯絡Email'),
    sa.Column('contact_phone', sa.String(length=30), nullable=True, comment='聯絡電話'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_short_name'), ['short_name'], unique=True)

    op.create_table('rackets',
    sa.Column('id', sa.Integer(), nullable=False, comment='球拍唯一識別碼'),
    sa.Column('brand', sa.String(length=50), nullable=False, comment='品牌'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='型號名稱'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rackets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rackets_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_rackets_model_name'), ['model_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='使用者唯一識別碼'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='帳號 (登入用)'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='電子郵件 (通常用於登入或通知)'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='雜湊後的密碼'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='暱稱 (顯示名稱)'),
    sa.Column('role', sa.Enum('admin', 'member', 'coach', 'cadre', name='user_role_enum'), nullable=False, comment='使用者角色'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最後更新時間'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='帳號是否啟用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False, comment='隊員唯一識別碼'),
    sa.Column('name', sa.String(length=80), nullable=False, comment='真實姓名'),
    sa.Column('student_id', sa.String(length=20), nullable=True, comment='學號'),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum_members'), nullable=True, comment='性別'),
    sa.Column('blood_type', sa.Enum('A', 'B', 'AB', 'O', 'unknown', name='blood_type_enum_members'), nullable=True, comment='血型'),
    sa.Column('position', sa.Enum('front', 'back', 'versatile', name='player_position_enum_members'), nullable=True, comment='擅長位置'),
    sa.Column('joined_date', sa.Date(), nullable=True, comment='入隊日期'),
    sa.Column('leaved_date', sa.Date(), nullable=True, comment='離隊日期 (若已離隊)'),
    sa.Column('mu', sa.Float(), nullable=False, comment='TrueSkill μ (平均實力)'),
    sa.Column('sigma', sa.Float(), nullable=False, comment='TrueSkill σ (實力不確定性)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='關於此隊員的備註'),
    sa.Column('organization_id', sa.Integer(), nullable=True, comment='所屬組織ID'),
    sa.Column('racket_id', sa.Integer(), nullable=True, comment='使用球拍ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='對應的使用者帳號ID'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_members_organization_id'),
    sa.ForeignKeyConstraint(['racket_id'], ['rackets.id'], name='fk_members_racket_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_members_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_racket_id'), ['racket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_members_user_id'), ['user_id'], unique=True)

    op.create_table('match_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='比賽記錄唯一識別碼'),
    sa.Column('match_date', sa.Date(), nullable=False, comment='比賽日期'),
    sa.Column('match_type', sa.Enum('games_5', 'games_7', 'games_9', name='match_type_enum_match_records'), nullable=False, comment='比賽類型'),
    sa.Column('match_format', sa.Enum('singles', 'doubles', 'mixed_doubles', name='match_format_enum_match_records'), nullable=False, comment='賽制'),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player3_id', sa.Integer(), nullable=False),
    sa.Column('player4_id', sa.Integer(), nullable=True),
    sa.Column('a_games', sa.Integer(), nullable=False, comment='A方贏得的總局數'),
    sa.Column('b_games', sa.Integer(), nullable=False, comment='B方贏得的總局數'),
    sa.Column('side_a_outcome', sa.Enum('win', 'loss', 'pending', name='outcome_enum_match_records'), nullable=False, comment='A方視角的比賽結果 (勝/負)'),
    sa.ForeignKeyConstraint(['player1_id'], ['members.id'], name='fk_match_records_p1_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player2_id'], ['members.id'], name='fk_match_records_p2_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player3_id'], ['members.id'], name='fk_match_records_p3_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player4_id'], ['members.id'], name='fk_match_records_p4_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_records_match_date'), ['match_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_records_player1_id'), ['player1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_records_player2_id'), ['player2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_records_player3_id'), ['player3_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_records_player4_id'), ['player4_id'], unique=False)

    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='該球員本場比賽的特殊記錄'),
    sa.ForeignKeyConstraint(['match_id'], ['match_records.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='_match_player_stats_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_records_player4_id'))
        batch_op.drop_index(batch_op.f('ix_match_records_player3_id'))
        batch_op.drop_index(batch_op.f('ix_match_records_player2_id'))
        batch_op.drop_index(batch_op.f('ix_match_records_player1_id'))
        batch_op.drop_index(batch_op.f('ix_match_records_match_date'))

    op.drop_table('match_records')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_members_student_id'))
        batch_op.drop_index(batch_op.f('ix_members_racket_id'))
        batch_op.drop_index(batch_op.f('ix_members_organization_id'))

    op.drop_table('members')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rackets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rackets_model_name'))
        batch_op.drop_index(batch_op.f('ix_rackets_brand'))

    op.drop_table('rackets')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_short_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_match_date'))

    op.drop_table('matches')
    # ### end Alembic commands ###
