"""Create initial tables or describe model changes

Revision ID: 93041ed4aef2
Revises: 
Create Date: 2025-05-20 08:04:57.776397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93041ed4aef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='賽事名稱 (例：113學年度大專盃淘汰賽 vs 台灣大學)'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='賽事日期'),
    sa.Column('opponent_team_overall', sa.String(length=100), nullable=True, comment='對手隊伍總稱'),
    sa.Column('nature', sa.Enum('FRIENDLY', 'INTERNAL_RANKING', 'PRACTISE', 'NIAG', name='overallmatchnatureenum'), nullable=True, comment='整體賽事性質'),
    sa.Column('venue', sa.String(length=100), nullable=True, comment='比賽地點'),
    sa.Column('event_notes', sa.Text(), nullable=True, comment='團隊賽事備註'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('student_id', sa.String(length=20), nullable=True, comment='學號'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True, comment='性別'),
    sa.Column('position', sa.Enum('BACK', 'FRONT', 'VERSATILE', name='positionenum'), nullable=True, comment='位置'),
    sa.Column('score', sa.Integer(), nullable=False, comment='積分'),
    sa.Column('racket', sa.String(length=100), nullable=True, comment='球拍'),
    sa.Column('join_date', sa.Date(), nullable=True, comment='入隊日期'),
    sa.Column('leave_date', sa.Date(), nullable=True, comment='離隊日期'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否為現役隊員'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備註'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('match_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_event_id', sa.Integer(), nullable=True, comment='所屬團隊賽事ID'),
    sa.Column('player1_id', sa.Integer(), nullable=False, comment='我方球員1 ID'),
    sa.Column('player2_id', sa.Integer(), nullable=True, comment='我方球員2 ID (雙打時)'),
    sa.Column('opponent_player1_name', sa.String(length=100), nullable=True, comment='對方球員1姓名'),
    sa.Column('opponent_player2_name', sa.String(length=100), nullable=True, comment='對方球員2姓名 (雙打時)'),
    sa.Column('match_date', sa.Date(), nullable=False, comment='單場比賽日期'),
    sa.Column('match_type', sa.Enum('SINGLES', 'DOUBLES', 'MIXED_DOUBLES', name='matchtypeenum'), nullable=False, comment='單打/雙打'),
    sa.Column('our_score_str', sa.String(length=50), nullable=True, comment='我方得分 (例: 6,6 / 7-5,6-2)'),
    sa.Column('opponent_score_str', sa.String(length=50), nullable=True, comment='對方得分 (例: 2,3 / 6-7,2-6)'),
    sa.Column('outcome', sa.Enum('WIN', 'LOSS', 'NOT_PLAYED', name='outcomeenum'), nullable=True, comment='比賽結果 (勝/負)'),
    sa.Column('point_order_in_event', sa.String(length=50), nullable=True, comment='在團隊賽中的點數/順序 (例: 第一點單打, 第二點雙打)'),
    sa.Column('match_notes', sa.Text(), nullable=True, comment='單場比賽備註'),
    sa.ForeignKeyConstraint(['player1_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_event_id'], ['team_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False, comment='對應的單場比賽ID'),
    sa.Column('player_id', sa.Integer(), nullable=False, comment='對應的球員ID'),
    sa.Column('aces', sa.Integer(), nullable=True, comment='Ace球數量'),
    sa.Column('double_faults', sa.Integer(), nullable=True, comment='雙發失誤數量'),
    sa.Column('first_serves_in', sa.Integer(), nullable=True, comment='一發進球數'),
    sa.Column('first_serves_total', sa.Integer(), nullable=True, comment='一發總數'),
    sa.Column('second_serves_in', sa.Integer(), nullable=True, comment='二發進球數'),
    sa.Column('second_serves_total', sa.Integer(), nullable=True, comment='二發總數'),
    sa.Column('winners', sa.Integer(), nullable=True, comment='致勝球數量 (不含Ace)'),
    sa.Column('unforced_errors', sa.Integer(), nullable=True, comment='非受迫性失誤數量'),
    sa.Column('forced_errors_caused', sa.Integer(), nullable=True, comment='造成對手受迫性失誤數量'),
    sa.Column('net_points_won', sa.Integer(), nullable=True, comment='網前得分'),
    sa.Column('net_points_played', sa.Integer(), nullable=True, comment='總上網次數'),
    sa.Column('break_points_won', sa.Integer(), nullable=True, comment='破發點得分數'),
    sa.Column('break_points_saved', sa.Integer(), nullable=True, comment='救回的破發點數'),
    sa.Column('break_points_opportunities', sa.Integer(), nullable=True, comment='總破發點機會數'),
    sa.Column('total_points_won', sa.Integer(), nullable=True, comment='總得分'),
    sa.Column('custom_stat_field_1', sa.String(length=255), nullable=True, comment='自訂統計欄位1'),
    sa.Column('custom_stat_field_2', sa.Float(), nullable=True, comment='自訂統計欄位2'),
    sa.ForeignKeyConstraint(['match_id'], ['match_records.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='_match_player_stats_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('match_records')
    op.drop_table('team_members')
    op.drop_table('team_events')
    # ### end Alembic commands ###
