"""update rating system

Revision ID: af252745d22b
Revises: 3dcdf7b283b0
Create Date: 2025-05-23 06:14:36.495376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af252745d22b'
down_revision = '3dcdf7b283b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mu', sa.Float(), nullable=False, comment='TrueSkill μ'))
        batch_op.add_column(sa.Column('sigma', sa.Float(), nullable=False, comment='TrueSkill σ'))
        batch_op.drop_column('organization_id')
        batch_op.drop_column('score')
        batch_op.drop_column('racket')
        batch_op.drop_column('join_date')
        batch_op.drop_column('leave_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_date', sa.DATE(), autoincrement=False, nullable=True, comment='離隊日期'))
        batch_op.add_column(sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=True, comment='入隊日期'))
        batch_op.add_column(sa.Column('racket', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='球拍'))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False, comment='積分'))
        batch_op.add_column(sa.Column('organization_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='單位'))
        batch_op.drop_column('sigma')
        batch_op.drop_column('mu')

    # ### end Alembic commands ###
